"""stage1 structured domain

Revision ID: 3ce5b254da1a
Revises:
Create Date: 2026-09-24 18:00:02.770248
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3ce5b254da1a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this version's schema changes."""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('ministry', sa.String(length=180), nullable=True),
    sa.Column('scope', sa.Enum('central', 'state', 'ut', name='schemescope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.Enum('unknown', 'active', 'paused', 'closed', name='schemestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(scope = 'central' AND state_code IS NULL) OR (scope IN ('state', 'ut') AND state_code IS NOT NULL)", name=op.f('ck_schemes_scope_matches_state_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('beneficiary_age', sa.Integer(), nullable=True),
    sa.Column('beneficiary_relationship', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('annual_family_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_band', sa.String(length=60), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=60), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('education_level', sa.String(length=80), nullable=True),
    sa.Column('is_farmer', sa.Boolean(), nullable=True),
    sa.Column('landholding_acres', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('residence_type', sa.String(length=20), nullable=True),
    sa.Column('disability_status', sa.String(length=60), nullable=True),
    sa.Column('scheme_interests', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age IS NULL OR (age >= 0 AND age <= 120)', name=op.f('ck_user_profiles_valid_age')),
    sa.CheckConstraint('annual_family_income IS NULL OR annual_family_income >= 0', name=op.f('ck_user_profiles_nonnegative_income')),
    sa.CheckConstraint('beneficiary_age IS NULL OR (beneficiary_age >= 0 AND beneficiary_age <= 120)', name=op.f('ck_user_profiles_valid_beneficiary_age')),
    sa.CheckConstraint('landholding_acres IS NULL OR landholding_acres >= 0', name=op.f('ck_user_profiles_nonnegative_land')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('session_id', name=op.f('uq_user_profiles_session_id'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('guideline', 'notification', 'gazette', 'ministry_page', 'official_api', 'government_aggregator', 'press_release', 'other', name='sourcetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('tier', sa.Enum('tier_1', 'tier_2', 'tier_3', name='sourcetier', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('authority_score >= 0 AND authority_score <= 100', name=op.f('ck_sources_authority_score_range')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_sources_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_scheme_id'), 'sources', ['scheme_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('unverified', 'current', 'superseded', name='documentstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to', name=op.f('ck_documents_valid_effective_window')),
    sa.CheckConstraint('page_count IS NULL OR page_count >= 0', name=op.f('ck_documents_page_count_nonnegative')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.String(length=80), nullable=False),
    sa.Column('parent_rule_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('group', 'condition', name='rulekind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('group_operator', sa.Enum('all', 'any', name='groupoperator', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('profile_field', sa.Enum('age', 'beneficiary_age', 'beneficiary_relationship', 'gender', 'state_code', 'district', 'annual_family_income', 'income_band', 'occupation', 'employment_status', 'is_student', 'education_level', 'is_farmer', 'landholding_acres', 'residence_type', 'disability_status', name='profilefield', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('comparison_operator', sa.Enum('eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'not_in', 'between', 'contains', 'exists', name='comparisonoperator', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('expected_value', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=True),
    sa.Column('machine_verified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(kind = 'group' AND group_operator IS NOT NULL AND profile_field IS NULL AND comparison_operator IS NULL AND expected_value IS NULL) OR (kind = 'condition' AND group_operator IS NULL AND profile_field IS NOT NULL AND comparison_operator IS NOT NULL)", name=op.f('ck_eligibility_rules_valid_rule_shape')),
    sa.CheckConstraint('priority >= 0', name=op.f('ck_eligibility_rules_nonnegative_priority')),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['eligibility_rules.id'], name=op.f('fk_eligibility_rules_parent_rule_id_eligibility_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_eligibility_rules_scheme_id_schemes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_eligibility_rules_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_rules'))
    )
    op.create_index(op.f('ix_eligibility_rules_parent_rule_id'), 'eligibility_rules', ['parent_rule_id'], unique=False)
    op.create_index(op.f('ix_eligibility_rules_scheme_id'), 'eligibility_rules', ['scheme_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('heading', sa.String(length=250), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('heading_path', sa.JSON(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_chunks_chunk_index_nonnegative')),
    sa.CheckConstraint('page_start IS NULL OR page_end IS NULL OR page_start <= page_end', name=op.f('ck_chunks_valid_page_range')),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name=op.f('ck_chunks_token_count_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this version's schema changes."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_eligibility_rules_scheme_id'), table_name='eligibility_rules')
    op.drop_index(op.f('ix_eligibility_rules_parent_rule_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_sources_scheme_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('user_profiles')
    op.drop_table('schemes')
    # ### end Alembic commands ###
